[project]
name = "SEP"
version = "0.1.0"
description = "Swedish Event Planners"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-extensions>=3.2.3",
    "django>=5.1.2",
]
