# Generated by Django 4.2.12 on 2024-10-26 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SEP', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Meeting date')),
                ('time', models.TimeField(verbose_name='Meeting time')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Meeting members (excl. client)')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Initial budget estimation')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('cs_approved', 'APPROVED BY CUSTOMER SERVICE'), ('cs_rejected', 'REJECTED BY CUSTOMER SERVICE'), ('fin_review', 'REVIEWED BY THE FINANCIAL MANAGER'), ('admin_approved', 'APPROVED BY THE ADMINISTRATION MANAGER'), ('admin_rejected', 'REJECTED BY THE ADMINISTRATION MANAGER')], default='pending', max_length=20, verbose_name='project status')),
                ('financial_feedback', models.TextField(blank=True, null=True, verbose_name='feedback from financial dpt.')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEP.customer', verbose_name='Project client')),
                ('meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.meeting', verbose_name='Initial client meeting')),
            ],
        ),
    ]
