# Generated by Django 5.1.2 on 2024-10-28 12:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEP', '0002_remove_employee_name'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SEP.customer', verbose_name='Project client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_budget',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial budget estimation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='initial_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.rawrequest', verbose_name='Initial request'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'DRAFT'), ('pending', 'PENDING'), ('cs_approved', 'APPROVED BY CUSTOMER SERVICE'), ('cs_rejected', 'REJECTED BY CUSTOMER SERVICE'), ('fin_review', 'REVIEWED BY THE FINANCIAL MANAGER'), ('admin_approved', 'APPROVED BY THE ADMINISTRATION MANAGER'), ('admin_rejected', 'REJECTED BY THE ADMINISTRATION MANAGER')], default='draft', max_length=20, null=True, verbose_name='project status'),
        ),
        migrations.AlterField(
            model_name='rawrequest',
            name='available',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Available budget'),
        ),
    ]
