# Generated by Django 5.1.2 on 2024-10-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='financial_feedback_draft_status',
            field=models.BooleanField(default=False, verbose_name='Draft status of the financial feedback'),
        ),
    ]
