# Generated by Django 5.1.2 on 2024-10-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'DRAFT'), ('pending', 'PENDING'), ('cs_approved', 'APPROVED BY CUSTOMER SERVICE'), ('cs_rejected', 'REJECTED BY CUSTOMER SERVICE'), ('fin_review', 'REVIEWED BY THE FINANCIAL MANAGER'), ('admin_approved', 'APPROVED BY THE ADMINISTRATION MANAGER'), ('admin_rejected', 'REJECTED BY THE ADMINISTRATION MANAGER'), ('completed', 'COMPLETED')], default='draft', max_length=20, null=True, verbose_name='project status'),
        ),
    ]
