# Generated by Django 5.1.2 on 2024-10-30 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_task_completed_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expected_number_of_guests',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Expected number of guests'),
        ),
        migrations.AddField(
            model_name='project',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Project start date'),
        ),
        migrations.AddField(
            model_name='project',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Project end date'),
        ),
    ]
