# Generated by Django 5.1.2 on 2024-10-30 11:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_expected_number_of_guests_project_from_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitementPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('part', 'Part-time'), ('full', 'Full-time')], max_length=4)),
                ('department', models.CharField(choices=[('adm', 'Administration'), ('serv', 'Services'), ('prod', 'Production'), ('fina', 'Financial')], max_length=4)),
                ('min_years_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('title', models.CharField(max_length=100, verbose_name='Job title')),
                ('description', models.TextField(verbose_name='Job description')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event end date'),
        ),
        migrations.CreateModel(
            name='FinancialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_department', models.CharField(choices=[('adm', 'Administration'), ('serv', 'Services'), ('prod', 'Production'), ('fina', 'Financial')], max_length=4)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField(verbose_name='Reason for the request')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
