# Generated by Django 5.1.2 on 2024-10-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_recruitementpost_alter_project_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitementpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval of HR'), ('ongoing', 'Ongoing recruitment'), ('completed', 'Recruitment completed')], default='pending', max_length=20),
        ),
    ]
