# Generated by Django 5.1.2 on 2024-10-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_recruitementpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval of the financial manager'), ('approved', 'Approved by the financial manager'), ('rejected', 'Rejected by the financial manager')], default='pending', max_length=20),
        ),
    ]
